/** CONSTRAINTS.**/

/**EMPOLYEE**/
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_FK
FOREIGN KEY  (SUPER_SSN)REFERENCES EMPLOYEE(SSN);


/**ADEPARTMENT**/
ALTER TABLE DEPARTMENT ADD CONSTRAINT DEPARTMENT_FK
FOREIGN KEY  (Mgr_ssn)REFERENCES EMPLOYEE(SSN) ;

/**ADEPT_LOCATIONS**/
ALTER TABLE DEPT_LOCATIONS ADD CONSTRAINT DEPT_LOCATIONS_FK
FOREIGN KEY  (Dnumber)REFERENCES DEPARTMENT(Dnumber);
/**APROJECT**/
ALTER TABLE DEPPROJECT ADD CONSTRAINT DEPPROJECT_FK
FOREIGN KEY  (Dnum)REFERENCES DEPARTMENT(Dnumber);

/**AWORKS_ON**/
ALTER TABLE WORKS_ON ADD CONSTRAINT 
WORKS_ON_FK1 FOREIGN KEY  (ESSN) REFERENCES EMPLOYEE(SSN);
ALTER TABLE WORKS_ON ADD CONSTRAINT 
WORKS_ON_FK2 FOREIGN KEY  (Pno) REFERENCES PROJECT(pnumber);
/**ADEPENDENT**/
ALTER TABLE DEPENDENT ADD CONSTRAINT DEPENDENT_FK 
FOREIGN KEY (ESSN)REFERENCES EMPLOYEE(SSN);
/**
Set constraints EMPOLYEE_FK, 
DEPT_LOCATIONS_FK,
WORKS_ON_FK1,
WORKS_ON_FK2,
DEPENDENT_FK,
PROJECT_FK,
DEPARTMENT_FK,
EMPOLYEE_FK
deferred**/

commit;
