/**views**/
DROP VIEW DepMngView;
DROP VIEW RESEARCHEMP;
DROP VIEW PROJREPORT;
DROP VIEW PROJREPORTM1;

/** CONSTRAINTS.**/

/**EMPOLYEE**/
ALTER TABLE EMPLOYEE DROP CONSTRAINT EMPLOYEE_FK;
/**DEPARTMENT**/
ALTER TABLE DEPARTMENT DROP CONSTRAINT DEPARTMENT_FK;
/**DEPT_LOCATIONS**/
ALTER TABLE DEPT_LOCATIONS DROP CONSTRAINT DEPT_LOCATIONS_FK;
/**PROJECT**/
ALTER TABLE DEPPROJECT DROP CONSTRAINT DEPPROJECT_FK;
/**WORKS_ON**/
ALTER TABLE WORKS_ON DROP CONSTRAINT WORKS_ON_FK1;

/**DEPENDENT**/
ALTER TABLE DEPENDENT DROP CONSTRAINT DEPENDENT_FK;
commit;
/** TODO: ON DELETE AND ON UPDATE CASCADES**/

/**TABLES**/
DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;
DROP TABLE DEPT_LOCATIONS;
DROP TABLE DEPPROJECT;
DROP TABLE WORKS_ON;
DROP TABLE DEPENDENT;
commit;
