--SECTION 
ALTER TABLE SECTION ADD CONSTRAINT
SECTION_FK1 FOREIGN KEY (COURSE_NUMBER) REFERENCES COURSE(COURSE_NUMBER);

--GRADE_REPORT
ALTER TABLE GRADE_REPORT ADD CONSTRAINT 
GRADE_REPORT_FK1 FOREIGN KEY (STUDENT_NUMBER) REFERENCES STUDENT (STUDENT_NUMBER);
ALTER TABLE GRADE_REPORT ADD CONSTRAINT 
  GRADE_REPORT_FK2 FOREIGN KEY (SECTION_ID) REFERENCES SECTION (SECTION_IDENTIFIER);
-- PREREQUISITE
ALTER TABLE PREREQUISITE ADD CONSTRAINT
PREREQUISITE_FK1 FOREIGN KEY (COURSE_NUMBER) REFERENCES COURSE(COURSE_NUMBER) ;
ALTER TABLE PREREQUISITE ADD CONSTRAINT
PREREQUISITE_FK2 FOREIGN KEY (PREREQUISITE_NUMBER) REFERENCES COURSE(COURSE_NUMBER) ;
s