CREATE TABLE STUDENT (
	NAME VARCHAR(40),
	STUDENT_NUMBER Number(10),
	CLASS VARCHAR(10),
	MAJOR VARCHAR(10) ,
  PRIMARY KEY (STUDENT_NUMBER)
	);

CREATE TABLE COURSE (
	COURSE_NAME VARCHAR(40),
	COURSE_NUMBER VARCHAR(20),
	CREDIT_HOURS Number(10),
	DEPARTMENT VARCHAR(10),
	PRIMARY KEY (COURSE_NUMBER)
	);

CREATE TABLE SECTION (
	SECTION_IDENTIFIER Number(10),
	COURSE_NUMBER VARCHAR(10),
	SEMESTER VARCHAR(10),
	YEAR VARCHAR(10),
	INSTRUCTOR VARCHAR(40),
	PRIMARY KEY (SECTION_IDENTIFIER)
	);

CREATE TABLE GRADE_REPORT (
	STUDENT_NUMBER Number(10),
	SECTION_ID Number(10),
	GRADE VARCHAR(10),
	PRIMARY KEY (STUDENT_NUMBER,SECTION_ID)
	);

CREATE TABLE PREREQUISITE (
	COURSE_NUMBER VARCHAR(10),
	PREREQUISITE_NUMBER VARCHAR(10),
	PRIMARY KEY (COURSE_NUMBER,PREREQUISITE_NUMBER)
	);

COMMIT;